  apiVersion: v1
  kind: Pod
  metadata:
    name: waggoner-house-firebase-proxy
  spec:
    volumes:
      - name: ttyUSB1
        hostPath:
          path: /dev/ttyUSB1
      - name: waggoner-house-firebase-service-account
        secret:
          secretName: waggoner-house-firebase-service-account
          items:
            - key: waggoner-house-firebase-service-account.json
    containers:
      - name: quay.io/ozzieorca/waggoner-house-firebase-proxy
        image: node-firebase-proxy
        volumeMounts:
          - name: ttyUSB1
            mountPath: /dev/ttyUSB1
          - name: waggoner-house-firebase-service-account
            mountPath: /usr/src/app/secrets
            readOnly: true
        securityContext:
          privileged: true
