  apiVersion: v1
  kind: Pod
  metadata:
    name: waggoner-house-firebase-proxy
  spec:
    volumes:
      - name: tty-usb-1
        hostPath:
          path: /dev/ttyUSB1
      - name: waggoner-house-firebase-service-account
        secret:
          secretName: waggoner-house-firebase-service-account
    containers:
      - name: node-firebase-proxy
        image: quay.io/ozzieorca/waggoner-house-firebase-proxy
        volumeMounts:
          - name: tty-usb-1
            mountPath: /dev/ttyUSB1
          - name: waggoner-house-firebase-service-account
            mountPath: /app/secrets
            readOnly: true
        securityContext:
          privileged: true
